// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLimY0sV7-mrg9pywykBTlGwU4IO8kwE',
    appId: '1:81434582045:web:56838f4950de61caa43af4',
    messagingSenderId: '81434582045',
    projectId: 'tasks-joddb',
    authDomain: 'tasks-joddb.firebaseapp.com',
    storageBucket: 'tasks-joddb.firebasestorage.app',
    measurementId: 'G-1SEFFQZGYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVtUqJo5zyh-wp2Y3-BLwsOjaJL5YUmE',
    appId: '1:81434582045:android:b5483aed7caa2998a43af4',
    messagingSenderId: '81434582045',
    projectId: 'tasks-joddb',
    storageBucket: 'tasks-joddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhyCctJHCBbiIRuwqOlWIZECdWTreBYYc',
    appId: '1:81434582045:ios:22b4020e175c0d4ea43af4',
    messagingSenderId: '81434582045',
    projectId: 'tasks-joddb',
    storageBucket: 'tasks-joddb.firebasestorage.app',
    iosBundleId: 'com.example.tasksJoddb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhyCctJHCBbiIRuwqOlWIZECdWTreBYYc',
    appId: '1:81434582045:ios:22b4020e175c0d4ea43af4',
    messagingSenderId: '81434582045',
    projectId: 'tasks-joddb',
    storageBucket: 'tasks-joddb.firebasestorage.app',
    iosBundleId: 'com.example.tasksJoddb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmLimY0sV7-mrg9pywykBTlGwU4IO8kwE',
    appId: '1:81434582045:web:183c98ba2bca5c3da43af4',
    messagingSenderId: '81434582045',
    projectId: 'tasks-joddb',
    authDomain: 'tasks-joddb.firebaseapp.com',
    storageBucket: 'tasks-joddb.firebasestorage.app',
    measurementId: 'G-2P4LFYFT21',
  );
}
